"""Generate results/summary.txt from the CSV files produced by experiments.py and ablations.py."""

import os
import pandas as pd
import numpy as np


def fmt(v, width=6):
    return f"{v:>{width}.3f}"


def pivot_table(df, value_col, row='dataset', col='model'):
    return df.pivot_table(index=row, columns=col, values=value_col, aggfunc='mean')


def write_comparison_block(f, df, metric, label, col_order):
    piv = pivot_table(df, metric, col='model')
    piv = piv.reindex(columns=[c for c in col_order if c in piv.columns])
    f.write(f"\n\nMAIN COMPARISON -- {label}\n")
    f.write("-" * 70 + "\n\n")
    header = f"{'Dataset':<14s}" + "".join(f" | {c:>18s}" for c in piv.columns)
    f.write(header + "\n")
    f.write("-" * len(header) + "\n")
    for ds in piv.index:
        row = f"{ds:<14s}"
        for c in piv.columns:
            row += f" | {fmt(piv.loc[ds, c], 18)}"
        f.write(row + "\n")


def write_ablation_block(f, df, name, note=""):
    f.write(f"\n\nABLATION -- {name}\n")
    f.write("-" * 70 + "\n")
    if note:
        f.write(note + "\n")
    f.write("\n")
    val_col = 'test_mse_mean' if 'test_mse_mean' in df.columns else 'test_mse'
    piv = pivot_table(df, val_col, row='dataset', col='config')
    header = f"{'Dataset':<14s}" + "".join(f" | {c:>12s}" for c in piv.columns)
    f.write(header + "\n")
    f.write("-" * len(header) + "\n")
    for ds in piv.index:
        row = f"{ds:<14s}"
        for c in piv.columns:
            row += f" | {fmt(piv.loc[ds, c], 12)}"
        f.write(row + "\n")


def main():
    os.makedirs('results', exist_ok=True)
    comp = pd.read_csv('results/comparison_summary.csv')

    col_order = ['Ridge', 'CART', 'RandomForest', 'GradientBoosting',
                 'RHM (original)', 'ACGMT (top1, no-std)',
                 'ACGMT (top3, std)', 'ACGMT (full)']

    with open('results/summary.txt', 'w') as f:
        f.write("Experiment Results Summary (auto-generated by generate_summary.py)\n")
        f.write("=" * 70 + "\n")
        f.write("All ACGMT variants without pruning train on 100% of training data.\n")
        f.write("ACGMT (full) with pruning trains on 80% and prunes on 20% holdout.\n")
        f.write("5 seeds per (dataset, model); values are means across seeds.\n")
        f.write("Ensemble random_state varies with seed (total variability).\n")
        f.write("RandomForest uses n_jobs=1 (fair single-thread comparison).\n")
        f.write("Predict-time differences between RHM (row-by-row) and ACGMT\n")
        f.write("(vectorized) are partly implementation; fit time is fairer.\n")

        write_comparison_block(f, comp, 'test_mse_mean',
                               'Test MSE (lower is better)', col_order)
        write_comparison_block(f, comp, 'test_r2_mean',
                               'Test R² (higher is better)', col_order)
        write_comparison_block(f, comp, 'fit_time_mean',
                               'Fit Time in seconds', col_order)

        # Ablations
        for name, note in [
            ('topk', 'val_fraction=0 (full training data), no pruning.'),
            ('standardize', 'val_fraction=0 (full training data), no pruning.'),
            ('grid', 'val_fraction=0 (full training data), no pruning.'),
            ('pruning', 'Both conditions use val_fraction=0.2 (same 80% build set). Only pruning differs.'),
        ]:
            path = f'results/ablation_{name}_summary.csv'
            if os.path.exists(path):
                abl = pd.read_csv(path)
                write_ablation_block(f, abl, name, note)

    print("Generated results/summary.txt")


if __name__ == '__main__':
    main()
